package org.ibpnh.core.json;

/**
 * Date format enums.
 * 
 * @author Axel Collard Bovy
 *
 */
public enum E_DateFormat {
	
	DATE_FORMAT,
	DATE_TIME_FORMAT,
	DATE_TIME_FORMAT_WITHOUT_MILLISECONDS,
	DATE_TIME_FORMAT_WITHOUT_SECONDS,
	DATE_TIME_FORMAT_WITHOUT_SECONDS_AND_YEAR,
	DATE_FORMAT_WITHOUT_DAYS_SHORT,
	DATE_TIME_ISO6801_FORMAT,
	DATE_TIME_WITH_HYPHENS_WITHOUT_MILLISECONDS,
	HOUR_FORMAT;
	
}
